FROM python:3.7

RUN adduser --uid 1000 --gecos --quiet --disabled-password toolhub

RUN mkdir -p /srv/app /var/www/media /var/www/static \
    && chown toolhub.toolhub /srv/app /var/www/media /var/www/static
WORKDIR /srv/app

ENV DJANGO_SETTINGS_MODULE=toolhub.settings.env \
    DEBUG=false

#RUN apt-get update && apt-get -y install \
    #python3-dev \
    ## cleanup
    #&& rm -rf /var/lib/apt/lists/*

RUN curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
RUN . $HOME/.poetry/env
RUN export PATH="$HOME/.poetry/bin:$PATH"

COPY --chown=toolhub:toolhub pyproject.* ./
RUN python $HOME/.poetry/bin/poetry config settings.virtualenvs.create false

ARG POETRY_ARGS="--no-dev"
#RUN python $HOME/.poetry/bin/poetry install $POETRY_ARGS
RUN python $HOME/.poetry/bin/poetry self:update
RUN python $HOME/.poetry/bin/poetry install

COPY --chown=toolhub:toolhub . .

# vim:set filetype=dockerfile:
